name: 'predun_dbt'
version: '1.0.0'
profile: 'predun_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  predun_dbt:
    canonical:
      +schema: canonical
      alumnos:
        +materialized: table
        +full_refresh: true
      cursada_historica:
        +materialized: table
        +full_refresh: true
      porcentaje_avance:
        +materialized: table
        +full_refresh: true
    staging:
      +schema: staging
      +materialized: view
      alumnos_flat:
        +schema: staging
      cursada_historica_flat:
        +schema: staging
      porcentaje_avance_flat:
        +schema: staging
    marts:
      +schema: marts
      +materialized: table

    example:
      +materialized: view